name: Reset database notify Discord
on:
  workflow_run:
    workflows: [Reset Database]
    types:
      - completed
defaults:
  run:
    shell: bash
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Discord message
        env:
          ACTOR: "[${{github.event.workflow_run.actor.login}}](${{github.event.workflow_run.actor.html_url}})"
          CONCLUSION: "${{github.event.workflow_run.conclusion}}"
          DISCORD_WEBHOOK_URL: "${{secrets.DISCORD_WEBHOOK_URL}}"
          GH_TOKEN: "${{github.token}}"
          REPOSITORY: "${{github.repository}}"
          RUN_ID: "${{github.event.workflow_run.id}}"
          TIMESTAMP: "${{github.event.workflow_run.updated_at}}"
          WORKFLOW_ID: "${{github.event.workflow_run.workflow_id}}"
          DISPLAY_TITLE: "${{github.event.workflow_run.display_title}}"
        run: '"$GITHUB_WORKSPACE"/script/reset-database-notify-discord.bash'

