name: Update server
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.sql'
jobs:
  update_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update server
        env:
          ARTIFACT_SSH_KEY: '${{secrets.ARTIFACT_SSH_KEY}}'
          ARTIFACT_HOST: '${{secrets.ARTIFACT_HOST}}'
        run: 'cd "$GITHUB_WORKSPACE"/script && ./server-run-script.bash ./server/update.bash'

      - name: Send Discord message
        env:
          DISCORD_WEBHOOK_URL: '${{secrets.DISCORD_WEBHOOK_URL}}'
          ACTOR: "${{github.actor}}"
          COMMIT: "${{ github.event.head_commit.message }}"
        run: 'cd "$GITHUB_WORKSPACE"/script && ./discord-send-msg.bash "Serveur mis Ã  jour ($ACTOR - \`$COMMIT\`)"'
